---
version: 2

project_name: radosgw-assume

builds:
  - id: radosgw-assume
    main: ./cmd/radosgw-assume
    env:
      - CGO_ENABLED=0
    binary: radosgw-assume
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/fitbeard/radosgw-assume/internal/version.Version={{ .Version }}
      - -X github.com/fitbeard/radosgw-assume/internal/version.GitCommit={{ .ShortCommit }}
      - -X github.com/fitbeard/radosgw-assume/internal/version.BuildDate={{ .Date }}

archives:
  - id: radosgw-assume
    ids:
      - radosgw-assume
    name_template: radosgw-assume-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
    formats:
      - tar.gz

# Managed by release-please
changelog:
  disable: true

checksum:
  name_template: radosgw-assume-v{{ .Version }}-checksums.txt

brews:
  - name: radosgw-assume
    commit_author:
      name: fitbeard
      email: tadasas@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: https://github.com/fitbeard/radosgw-assume
    description: CLI tool for AWS STS role assumption with RadosGW.
    install: |
      bin.install "radosgw-assume"
    test: |
      system "radosgw-assume version"
    repository:
      owner: fitbeard
      name: homebrew-radosgw-assume
      branch: main
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
