package ui

import (
	"fmt"
)

// PrintUsage displays the help information for the application
func PrintUsage() {
	fmt.Println("Usage: radosgw-assume [OPTIONS] [PROFILE]")
	fmt.Println("       radosgw-assume (interactive profile selection)")
	fmt.Println("")
	fmt.Println("Options:")
	fmt.Println("  -h, --help                Show this help message and exit")
	fmt.Println("  -e, --env                 Use environment variables for configuration")
	fmt.Println("  -v, --verbose             Show verbose output with detailed information")
	fmt.Println("  -d, --duration DURATION   Session duration (default: 1h, min: 15m, max: 12h)")
	fmt.Println("                            Formats: '3600' (seconds), '60m' (minutes), '1h' (hours)")
	fmt.Println("  -s, --session NAME        Session name (default: radosgw-assume-TIMESTAMP)")
	fmt.Println("                            Only alphanumeric characters and dashes allowed")
	fmt.Println("")
	fmt.Println("Commands:")
	fmt.Println("  version                   Show version information")
	fmt.Println("")
	fmt.Println("Arguments:")
	fmt.Println("  PROFILE       Profile name from ~/.aws/config")
	fmt.Println("")
	fmt.Println("Examples:")
	fmt.Println("  radosgw-assume                        # Interactive selection, clean output")
	fmt.Println("  radosgw-assume myprofile              # Use specific profile, clean output")
	fmt.Println("  radosgw-assume --env                  # Use environment variables")
	fmt.Println("  radosgw-assume -d 2h myprofile        # 2-hour session duration")
	fmt.Println("  radosgw-assume -d 30m myprofile       # 30-minute session duration")
	fmt.Println("  radosgw-assume -d 15m myprofile       # 15-minute session duration (minimum)")
	fmt.Println("  radosgw-assume -s my-session profile  # Custom session name")
	fmt.Println("  eval $(radosgw-assume)                # Interactive with credential export")
	fmt.Println("  eval $(radosgw-assume myprofile)      # Direct profile with export")
	fmt.Println("  radosgw-assume --verbose              # Verbose output with detailed info")
	fmt.Println("")
	fmt.Println("Environment Variables (when using -e/--env):")
	fmt.Println("  RADOSGW_OIDC_PROVIDER     - OIDC provider URL (required, except for token auth)")
	fmt.Println("  RADOSGW_OIDC_CLIENT_ID    - OIDC client ID (required, except for token auth)")
	fmt.Println("  AWS_ENDPOINT_URL          - RadosGW endpoint URL (required)")
	fmt.Println("  RADOSGW_ROLE_ARN          - Role ARN to assume (required)")
    fmt.Println("  RADOSGW_ROLE_SESSION_NAME - Role session name (optional, default: radosgw-assume-TIMESTAMP)")
	fmt.Println("  RADOSGW_OIDC_AUTH_TYPE    - Auth type: device|browser|token (optional, default: device)")
	fmt.Println("  RADOSGW_OIDC_TOKEN        - Pre-existing OIDC token (required for token auth type)")
	fmt.Println("  RADOSGW_OIDC_SCOPE        - OIDC scope (optional, default: openid, ignored for token auth)")
	fmt.Println("  RADOSGW_SSL_VERIFY        - SSL verification: true|false (optional, default: true)")
	fmt.Println("")
	fmt.Println("Configuration:")
	fmt.Println("  Edit ~/.aws/config with RadosGW and OIDC settings")
	fmt.Println("  See documentation and configuration format details at https://github.com/fitbeard/radosgw-assume")
}
