package ui

import (
	"fmt"
	"io"
	"os"
)

// PrintUsage displays the help information for the application
func PrintUsage() {
	FprintUsage(os.Stdout)
}

// FprintUsage writes the help information to w.
func FprintUsage(w io.Writer) {
	_, _ = fmt.Fprintln(w, "Usage: radosgw-assume [OPTIONS]")
	_, _ = fmt.Fprintln(w, "       radosgw-assume exec [OPTIONS] -- COMMAND [ARG...]")
	_, _ = fmt.Fprintln(w, "       radosgw-assume shell [OPTIONS]")
	_, _ = fmt.Fprintln(w, "       radosgw-assume credential-process (-p PROFILE | --env) [OPTIONS]")
	_, _ = fmt.Fprintln(w, "       radosgw-assume cache <status|clear>")
	_, _ = fmt.Fprintln(w, "       radosgw-assume (interactive profile selection)")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Options:")
	_, _ = fmt.Fprintln(w, "  -h, --help                Show this help message and exit")
	_, _ = fmt.Fprintln(w, "  -e, --env                 Use environment variables for configuration")
	_, _ = fmt.Fprintln(w, "  -p, --profile PROFILE     Use a specific profile from ~/.aws/config")
	_, _ = fmt.Fprintln(w, "  -v, --verbose             Show verbose output with detailed information")
	_, _ = fmt.Fprintln(w, "  -d, --duration DURATION   Session duration (default: 1h, min: 15m, max: 12h)")
	_, _ = fmt.Fprintln(w, "                            Formats: '3600' (seconds), '60m' (minutes), '1h' (hours)")
	_, _ = fmt.Fprintln(w, "  -s, --session NAME        Session name (default: radosgw-assume-TIMESTAMP)")
	_, _ = fmt.Fprintln(w, "                            Only alphanumeric characters and dashes allowed")
	_, _ = fmt.Fprintln(w, "      --show-credentials    Allow credential exports to be printed to a terminal")
	_, _ = fmt.Fprintln(w, "      --no-prompt           Keep the original prompt in an authenticated shell")
	_, _ = fmt.Fprintln(w, "      --no-cache            Bypass the credential-process cache")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Commands:")
	_, _ = fmt.Fprintln(w, "  exec                      Run a command with temporary credentials")
	_, _ = fmt.Fprintln(w, "  shell                     Start an interactive shell with temporary credentials")
	_, _ = fmt.Fprintln(w, "  credential-process        Emit AWS process credential provider JSON")
	_, _ = fmt.Fprintln(w, "  cache status              Show a non-secret credential cache summary")
	_, _ = fmt.Fprintln(w, "  cache clear               Remove cached temporary credentials")
	_, _ = fmt.Fprintln(w, "  version                   Show version information")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Examples:")
	_, _ = fmt.Fprintln(w, "  eval \"$(radosgw-assume)\"                               # Select and export a profile")
	_, _ = fmt.Fprintln(w, "  eval \"$(radosgw-assume -p myprofile)\"                  # Export a specific profile")
	_, _ = fmt.Fprintln(w, "  eval \"$(radosgw-assume --env)\"                         # Export environment configuration")
	_, _ = fmt.Fprintln(w, "  eval \"$(radosgw-assume -d 2h -p myprofile)\"            # Export a 2-hour session")
	_, _ = fmt.Fprintln(w, "  eval \"$(radosgw-assume -s my-session -p myprofile)\"    # Export with a custom session name")
	_, _ = fmt.Fprintln(w, "  source <(radosgw-assume)                               # Select and export with source")
	_, _ = fmt.Fprintln(w, "  source <(radosgw-assume -p myprofile)                  # Export a profile with source")
	_, _ = fmt.Fprintln(w, "  radosgw-assume --show-credentials -p myprofile         # Deliberately display credentials")
	_, _ = fmt.Fprintln(w, "  radosgw-assume --show-credentials --env                # Display environment-configured credentials")
	_, _ = fmt.Fprintln(w, "  radosgw-assume exec -- aws s3 ls                       # Select profile, then run once")
	_, _ = fmt.Fprintln(w, "  radosgw-assume exec -p myprofile -- aws s3 ls          # Use specific profile, then run once")
	_, _ = fmt.Fprintln(w, "  radosgw-assume shell                                   # Select profile, then start a shell")
	_, _ = fmt.Fprintln(w, "  radosgw-assume shell -p myprofile                      # Start a shell for a specific profile")
	_, _ = fmt.Fprintln(w, "  radosgw-assume credential-process -p myprofile         # Emit AWS credential_process JSON")
	_, _ = fmt.Fprintln(w, "  radosgw-assume credential-process -d 12h -p myprofile  # Request and cache a 12-hour session")
	_, _ = fmt.Fprintln(w, "  radosgw-assume cache status                            # Inspect cache without exposing credentials")
	_, _ = fmt.Fprintln(w, "  radosgw-assume cache clear                             # Remove all cached credentials")
	_, _ = fmt.Fprintln(w, "  eval \"$(radosgw-assume --verbose)\"                     # Export with detailed diagnostics")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Security:")
	_, _ = fmt.Fprintln(w, "  Credential exports are refused when stdout is a terminal unless --show-credentials is set.")
	_, _ = fmt.Fprintln(w, "  Capture them with eval/source, or avoid exporting with exec/shell.")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Environment Variables (when using -e/--env):")
	_, _ = fmt.Fprintln(w, "  RADOSGW_OIDC_PROVIDER      - OIDC issuer URL (required, except for token auth)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_OIDC_CLIENT_ID     - OIDC client ID (required, except for token auth)")
	_, _ = fmt.Fprintln(w, "  AWS_ENDPOINT_URL           - RadosGW endpoint URL (required)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_ROLE_ARN           - Role ARN to assume (required)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_ROLE_SESSION_NAME  - Role session name (optional, default: radosgw-assume-TIMESTAMP)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_OIDC_AUTH_TYPE     - Auth type: device|browser|token (optional, default: device)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_OIDC_TOKEN         - Pre-existing OIDC token (required for token auth type)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_OIDC_SCOPE         - OIDC scope (optional, default: openid, ignored for token auth)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_OIDC_PKCE_METHOD   - PKCE method: S256|plain (optional, default: S256)")
	_, _ = fmt.Fprintln(w, "  RADOSGW_SSL_VERIFY         - SSL verification: true|false|1|0 (optional, default: true)")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "Configuration:")
	_, _ = fmt.Fprintln(w, "  Edit ~/.aws/config with RadosGW and OIDC settings")
	_, _ = fmt.Fprintln(w, "  See documentation and configuration format details at https://github.com/fitbeard/radosgw-assume")
}
