---
name: lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - uses: golangci/golangci-lint-action@v9
